# Generated by Django 4.2.11 on 2025-04-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_likes_trip_tags_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
