# Generated by Django 4.2.11 on 2025-05-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_wishlist_trip_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
    ]
