# Generated by Django 4.2.11 on 2025-05-03 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_wishlist_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='image',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='locations',
        ),
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trips/')),
                ('is_main', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trips.trip')),
            ],
        ),
    ]
