# Generated by Django 4.2.11 on 2025-05-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_remove_trip_image_remove_trip_locations_tripimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(default=' ', upload_to='trips/'),
            preserve_default=False,
        ),
    ]
